# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: stupider_formatter 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "stupider_formatter".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Christoph Olszowka".freeze, "l33tname".freeze]
  s.date = "2021-11-20"
  s.description = "A stupid formatter for piping text through markup processors with a unified API".freeze
  s.email = "hi at l33t dot name".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/stupid_formatter.rb",
    "stupider_formatter.gemspec",
    "test/fixtures/erb_coderay_markdown_example.txt",
    "test/fixtures/erb_coderay_markdown_expectation.txt",
    "test/helper.rb",
    "test/test_erb_formatter.rb",
    "test/test_rdiscount_formatter.rb",
    "test/test_stupid_formatter.rb"
  ]
  s.homepage = "https://github.com/fliiiix/stupider_formatter".freeze
  s.rubygems_version = "3.2.3".freeze
  s.summary = "A stupid formatter for piping text through markup processors".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<rdiscount>.freeze, [">= 1.5.0"])
    s.add_runtime_dependency(%q<coderay>.freeze, [">= 0.9.0"])
    s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
  else
    s.add_dependency(%q<rdiscount>.freeze, [">= 1.5.0"])
    s.add_dependency(%q<coderay>.freeze, [">= 0.9.0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
  end
end

